# Generated by Django 2.0 on 2017-12-06 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='environment',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Organization'),
        ),
    ]
