# Generated by Django 2.0 on 2017-12-07 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GroupCI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Datacenter',
            fields=[
                ('ci_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cmdb.CI')),
                ('location', models.CharField(max_length=200, null=True)),
            ],
            bases=('cmdb.ci',),
        ),
        migrations.AddField(
            model_name='groupci',
            name='ci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.CI'),
        ),
        migrations.AddField(
            model_name='groupci',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Group'),
        ),
        migrations.AddField(
            model_name='group',
            name='cis',
            field=models.ManyToManyField(through='cmdb.GroupCI', to='cmdb.CI'),
        ),
        migrations.AddField(
            model_name='ci',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Organization'),
        ),
    ]
