# Generated by Django 2.0 on 2017-12-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20171207_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupci',
            name='ci',
        ),
        migrations.RemoveField(
            model_name='groupci',
            name='group',
        ),
        migrations.AlterField(
            model_name='group',
            name='cis',
            field=models.ManyToManyField(to='cmdb.CI'),
        ),
        migrations.DeleteModel(
            name='GroupCI',
        ),
    ]
