# Generated by Django 2.0 on 2017-12-08 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20171207_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ci',
            name='org',
        ),
        migrations.RemoveField(
            model_name='datacenter',
            name='ci_ptr',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='org',
        ),
        migrations.RemoveField(
            model_name='group',
            name='cis',
        ),
        migrations.DeleteModel(
            name='CI',
        ),
        migrations.DeleteModel(
            name='Datacenter',
        ),
        migrations.DeleteModel(
            name='Environment',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
