# Generated by Django 2.0 on 2017-12-08 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmdb', '0006_auto_20171208_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='CI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200, null=True)),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Environment')),
            ],
        ),
        migrations.CreateModel(
            name='Datacenter',
            fields=[
                ('ci_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cmdb.CI')),
                ('location', models.CharField(max_length=200, null=True)),
            ],
            bases=('cmdb.ci',),
        ),
        migrations.AddField(
            model_name='group',
            name='cis',
            field=models.ManyToManyField(to='cmdb.CI'),
        ),
        migrations.AddField(
            model_name='ci',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Organization'),
        ),
    ]
