# Generated by Django 2.0 on 2017-12-08 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_auto_20171208_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='env',
        ),
        migrations.RemoveField(
            model_name='group',
            name='cis',
        ),
        migrations.AddField(
            model_name='group',
            name='cis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.CI'),
        ),
        migrations.DeleteModel(
            name='Environment',
        ),
    ]
