# Generated by Django 2.0 on 2017-12-08 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0009_auto_20171208_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ci',
            name='group',
        ),
        migrations.RemoveField(
            model_name='ci',
            name='org',
        ),
        migrations.RemoveField(
            model_name='datacenter',
            name='ci_ptr',
        ),
        migrations.DeleteModel(
            name='CI',
        ),
        migrations.DeleteModel(
            name='Datacenter',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
