# Generated by Django 2.0 on 2017-12-08 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0011_auto_20171208_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacenter',
            name='group',
        ),
        migrations.RemoveField(
            model_name='datacenter',
            name='org',
        ),
        migrations.DeleteModel(
            name='Datacenter',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
