# Generated by Django 2.0 on 2017-12-08 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmdb', '0014_auto_20171208_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='CI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Datacenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('env', models.CharField(choices=[('NP', 'NON-PROD'), ('PR', 'PROD')], default='NP', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('ci_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cmdb.CI')),
                ('ip', models.CharField(max_length=50)),
                ('mem_G', models.IntegerField()),
                ('local_disk', models.CharField(max_length=50)),
                ('power_status', models.CharField(max_length=50)),
                ('env', models.CharField(choices=[('NP', 'NON-PROD'), ('PR', 'PROD')], default='NP', max_length=50)),
            ],
            bases=('cmdb.ci',),
        ),
        migrations.CreateModel(
            name='ServerModel',
            fields=[
                ('model_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cmdb.Model')),
            ],
            bases=('cmdb.model',),
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('ci_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cmdb.CI')),
                ('version', models.CharField(max_length=50)),
                ('env', models.CharField(choices=[('NP', 'NON-PROD'), ('PR', 'PROD')], default='NP', max_length=50)),
                ('license', models.CharField(max_length=50)),
            ],
            bases=('cmdb.ci',),
        ),
        migrations.AddField(
            model_name='model',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Organization'),
        ),
        migrations.AddField(
            model_name='datacenter',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Organization'),
        ),
        migrations.AddField(
            model_name='ci',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Group'),
        ),
        migrations.AddField(
            model_name='ci',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Organization'),
        ),
        migrations.CreateModel(
            name='Hypervisor',
            fields=[
                ('software_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cmdb.Software')),
            ],
            bases=('cmdb.software',),
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('software_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cmdb.Software')),
                ('family', models.CharField(max_length=50)),
            ],
            bases=('cmdb.software',),
        ),
        migrations.CreateModel(
            name='PhysicalServer',
            fields=[
                ('server_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cmdb.Server')),
                ('rack', models.CharField(max_length=50)),
                ('cpu_type', models.CharField(max_length=50)),
                ('cpu_speed', models.CharField(max_length=50)),
                ('cpu_sockets', models.IntegerField()),
                ('cpu_cores', models.IntegerField()),
                ('ext_disk', models.CharField(max_length=50)),
                ('serial', models.CharField(max_length=50)),
                ('maint_status', models.CharField(max_length=50)),
                ('maint_vendor', models.CharField(max_length=50)),
                ('maint_service_from', models.DateField()),
                ('maint_service_to', models.DateField()),
                ('check_date', models.DateField()),
                ('power_ports', models.IntegerField()),
                ('lan_ports', models.IntegerField()),
                ('fiber_ports', models.IntegerField()),
                ('fiber_cards', models.IntegerField()),
                ('fiber_card_model', models.CharField(max_length=50)),
            ],
            bases=('cmdb.server',),
        ),
        migrations.CreateModel(
            name='VirtualServer',
            fields=[
                ('server_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cmdb.Server')),
                ('cpu_num', models.IntegerField()),
                ('hypervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Hypervisor')),
                ('os', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.OS')),
            ],
            bases=('cmdb.server',),
        ),
        migrations.AddField(
            model_name='server',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ESXServer',
            fields=[
                ('physicalserver_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cmdb.PhysicalServer')),
                ('hypervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Hypervisor')),
            ],
            bases=('cmdb.physicalserver',),
        ),
        migrations.CreateModel(
            name='NONESXServer',
            fields=[
                ('physicalserver_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cmdb.PhysicalServer')),
                ('os', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.OS')),
            ],
            bases=('cmdb.physicalserver',),
        ),
        migrations.AddField(
            model_name='physicalserver',
            name='check_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='physicalserver',
            name='datacenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Datacenter'),
        ),
        migrations.AddField(
            model_name='physicalserver',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.ServerModel'),
        ),
        migrations.AddField(
            model_name='virtualserver',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.ESXServer'),
        ),
    ]
