# Generated by Django 2.0 on 2017-12-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0015_auto_20171208_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='os',
            name='family',
        ),
        migrations.AlterField(
            model_name='software',
            name='license',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
